// Strong override of libc's memset (a weak alias in emscripten's libc),
// routing all memset calls through the wasm memory.fill instruction via
// emscripten's own bulk-memory implementation (emscripten_memset_bulkmem.S,
// referenced from the emsdk at build time).
//
// Emscripten only selects the memory.fill memset for -Oz builds
// (EMSCRIPTEN_OPTIMIZE_FOR_OZ); this shim provides it at -O2 without
// changing anything else. Runtimes that execute memory.fill natively
// (e.g. Go code generated by wasm2go) fill at memmove speed instead of
// running the scalar musl loop; measured neutral on wazero.
#include <stddef.h>

void *_emscripten_memset_bulkmem(void *s, int c, size_t n);

void *memset(void *s, int c, size_t n) {
  return _emscripten_memset_bulkmem(s, c, n);
}
