blank_issues_enabled: true
contact_links:
  - name: PDFium group
    url: https://groups.google.com/g/pdfium
    about: For general questions, feature requests, or issues with PDFium itself, please use the official PDFium discussion group.
