name: Build one

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      target_os:
        description: Target OS
        type: choice
        default: 'emscripten'
        options:
          - android
          - emscripten
          - ios
          - linux
          - mac
          - win
      target_cpu:
        description: Target CPU
        type: choice
        default: 'wasm'
        options:
          - wasm
      target_environment:
        description: Target environment
        type: choice
        default: ''
        options:
          - ''
      emsdk_version:
        description: Emscripten SDK
        type: string
        required: false
        default: 3.1.56
      use_system_libjpeg:
        description: Use the Emscripten system libjpeg
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ${{ github.event.inputs.target_os }}
      target_cpu: ${{ github.event.inputs.target_cpu }}
      target_environment: ${{ github.event.inputs.target_environment }}
      enable_v8: false
      emsdk_version: ${{ github.event.inputs.emsdk_version }}
      use_system_libjpeg: ${{ github.event.inputs.use_system_libjpeg == 'true' }}
