name: Build Wasm

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: ""
      version:
        description: PDFium version
        required: false
        default: ""
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false

jobs:
  query:
    name: Query Chromium infos
    runs-on: ubuntu-latest
    if: github.event.inputs.branch == '' || github.event.inputs.version = ''
    steps:
    - name: Get Chrome version
      id: chromium
      timeout-minutes: 5
      shell: bash
      run: |
        VERSION=$(git ls-remote --sort version:refname --tags https://chromium.googlesource.com/chromium/src '*.*.*.0' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+.0' | tail -n1)
        BUILD=$(echo "$VERSION" | cut -d. -f3)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "branch=chromium/$BUILD" >> $GITHUB_OUTPUT
  wasm:
    name: WASM
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        emsdk_version: [3.1.12, 3.1.34]
    with:
      branch: ${{ github.event.inputs.branch || jobs.query.chromium.outputs.branch }}
      version: ${{ github.event.inputs.version || jobs.query.chromium.outputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: wasm
      target_cpu: wasm
      enable_v8: false
      emsdk_version: ${{ matrix.emsdk_version }}

  nuget:
    name: Build NuGet packages
    runs-on: windows-latest
    needs:
      - wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: nuget
      - name: Pack
        shell: bash
        run: |
          for NUSPEC in nuget/*.nuspec; do
            echo "::group::$NUSPEC"
            nuget pack "$NUSPEC" -properties "version=${{ github.event.inputs.version || '0.0.0.0' }};branch=${GITHUB_REF#refs/heads/};commit=${GITHUB_SHA}"
            echo "::endgroup::"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: NuGet packages
          path: '*.nupkg'