name: Build one

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      emsdk_version:
        description: Emscripten SDK
        type: string
        required: false
        default: 3.1.34
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      target_os:
        description: Target OS (wasm|win)
        type: string
        required: true
        default: "wasm"
      target_cpu:
        description: Target CPU (arm64|x64|x86|wasm)
        type: string
        required: true
        default: "wasm"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ${{ github.event.inputs.target_os }}
      target_cpu: ${{ github.event.inputs.target_cpu }}
      target_libc: ''
      enable_v8: false
      emsdk_version: ${{ github.event.inputs.emsdk_version }}