name: Build all

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false

jobs:
  android_arm:
    name: Android ARM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm
      enable_v8: false

  android_arm_v8:
    name: Android ARM V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_arm
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm
      enable_v8: true

  android_arm64:
    name: Android ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm64
      enable_v8: false

  android_arm64_v8:
    name: Android ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: arm64
      enable_v8: true

  android_x64:
    name: Android x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x64
      enable_v8: false

  android_x64_v8:
    name: Android x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x64
      enable_v8: true

  android_x86:
    name: Android x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x86
      enable_v8: false

  android_x86_v8:
    name: Android x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: android_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: android
      target_cpu: x86
      enable_v8: true

  ios_arm64:
    name: iOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: arm64
      enable_v8: false

  ios_arm64_v8:
    name: iOS ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: ios_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: arm64
      enable_v8: true

  ios_x64:
    name: iOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: x64
      enable_v8: false

  ios_x64_v8:
    name: iOS x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: ios_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: ios
      target_cpu: x64
      enable_v8: true

  linux_arm:
    name: Linux ARM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm
      enable_v8: false

  linux_arm_v8:
    name: Linux ARM V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_arm
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm
      enable_v8: true

  linux_arm64:
    name: Linux ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm64
      enable_v8: false

  linux_arm64_v8:
    name: Linux ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm64
      enable_v8: true

  linux_x64:
    name: Linux x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      enable_v8: false

  linux_x64_v8:
    name: Linux x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      enable_v8: true

  linux_x86:
    name: Linux x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      enable_v8: false

  linux_x86_v8:
    name: Linux x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      enable_v8: true

  linux_musl_x64:
    name: Linux musl x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      target_libc: musl
      enable_v8: false

  linux_musl_x64_v8:
    name: Linux musl x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_musl_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      target_libc: musl
      enable_v8: true

  linux_musl_x86:
    name: Linux musl x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      target_libc: musl
      enable_v8: false

  linux_musl_x86_v8:
    name: Linux musl x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: linux_musl_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x86
      target_libc: musl
      enable_v8: true

  mac_arm64:
    name: macOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: arm64
      enable_v8: false

  mac_arm64_v8:
    name: macOS ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: mac_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: arm64
      enable_v8: true

  mac_x64:
    name: macOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: x64
      enable_v8: false

  mac_x64_v8:
    name: macOS x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: mac_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: x64
      enable_v8: true

  win_arm64:
    name: Windows ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: arm64
      enable_v8: false

  win_arm64_v8:
    name: Windows ARM64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: win_arm64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: arm64
      enable_v8: true

  win_x64:
    name: Windows x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x64
      enable_v8: false

  win_x64_v8:
    name: Windows x64 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: win_x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x64
      enable_v8: true

  win_x86:
    name: Windows x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x86
      enable_v8: false

  win_x86_v8:
    name: Windows x86 V8
    if: github.event.inputs.enable_v8 == 'true'
    needs: win_x86
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x86
      enable_v8: true

  wasm:
    name: WASM
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: wasm
      target_cpu: wasm
      enable_v8: false

  mac_univ:
    name: macOS univ
    needs:
      - mac_arm64
      - mac_x64
    uses: ./.github/workflows/mac-univ.yml
    with:
      artifact_x64: ${{ needs.mac_x64.outputs.artifact }}
      artifact_arm64: ${{ needs.mac_arm64.outputs.artifact }}

  mac_univ_v8:
    name: macOS univ V8
    needs:
      - mac_arm64_v8
      - mac_x64_v8
    uses: ./.github/workflows/mac-univ.yml
    with:
      artifact_x64: ${{ needs.mac_x64_v8.outputs.artifact }}
      artifact_arm64: ${{ needs.mac_arm64_v8.outputs.artifact }}

  nuget:
    name: Build NuGet packages
    runs-on: windows-latest
    needs:
      - android_arm
      - android_arm_v8
      - android_arm64
      - android_arm64_v8
      - android_x64
      - android_x64_v8
      - android_x86
      - android_x86_v8
      - ios_arm64
      - ios_arm64_v8
      - ios_x64
      - ios_x64_v8
      - linux_arm
      - linux_arm_v8
      - linux_arm64
      - linux_arm64_v8
      - linux_x64
      - linux_x64_v8
      - linux_x86
      - linux_x86_v8
      - linux_musl_x64
      - linux_musl_x64_v8
      - linux_musl_x86
      - linux_musl_x86_v8
      - mac_arm64
      - mac_arm64_v8
      - mac_x64
      - mac_x64_v8
      - wasm
      - win_arm64
      - win_arm64_v8
      - win_x64
      - win_x64_v8
      - win_x86
      - win_x86_v8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: nuget
      - name: Pack
        shell: bash
        run: |
          for NUSPEC in nuget/*.nuspec; do
            echo "::group::$NUSPEC"
            nuget pack "$NUSPEC" -properties "version=${{ github.event.inputs.version || '0.0.0.0' }};branch=${GITHUB_REF#refs/heads/};commit=${GITHUB_SHA}"
            echo "::endgroup::"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: NuGet packages
          path: '*.nupkg'
      - name: Push to nuget.org
        if: env.NUGET_API_KEY && startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version
        run: nuget push -Source nuget.org -ApiKey ${{ secrets.NUGET_API_KEY }} *.nupkg
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY  }}

  publish:
    name: Publish Release
    if: startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version
    runs-on: ubuntu-latest
    needs:
      - android_arm
      - android_arm_v8
      - android_arm64
      - android_arm64_v8
      - android_x64
      - android_x64_v8
      - android_x86
      - android_x86_v8
      - ios_arm64
      - ios_arm64_v8
      - ios_x64
      - ios_x64_v8
      - linux_arm
      - linux_arm_v8
      - linux_arm64
      - linux_arm64_v8
      - linux_musl_x64
      - linux_musl_x64_v8
      - linux_musl_x86
      - linux_musl_x86_v8
      - linux_x64
      - linux_x64_v8
      - linux_x86
      - linux_x86_v8
      - mac_arm64
      - mac_arm64_v8
      - mac_univ
      - mac_univ_v8
      - mac_x64
      - mac_x64_v8
      - wasm
      - win_arm64
      - win_arm64_v8
      - win_x64
      - win_x64_v8
      - win_x86
      - win_x86_v8
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create tarballs
        run: |
          for DIR in pdfium-*; do
            echo "::group::$DIR"
            (cd $DIR; tar czf ../$DIR.tgz *)
            echo "::endgroup::"
          done
      - name: Write release body
        run: echo 'This version was built with branch `${{ github.event.inputs.branch }}` of PDFium' > RELEASE.md
      - name: Get changes
        continue-on-error: true
        run: |
          CURRENT_REV=${{ github.event.inputs.branch }}
          PREVIOUS_REV=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name")
          git clone -b "${{ github.event.inputs.branch }}" https://pdfium.googlesource.com/pdfium.git
          cat <<END >> RELEASE.md
          ### Changes
          Commits between \`$PREVIOUS_REV\` and \`$CURRENT_REV\`:
          END
          git -C "pdfium" log origin/${PREVIOUS_REV}.. --pretty=format:'* [%s](https://pdfium.googlesource.com/pdfium/+/%H)' >> RELEASE.md
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PDFium ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.branch }}
          artifacts: "pdfium-*.tgz"
